# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    host.date_filter:
        parent:    'api_platform.doctrine.orm.date_filter'
        arguments: [ { updated: ~ } ] ## critical this NEEDS to be the property in the Entity
        tags:      [ { name: 'api_platform.filter', id: 'host.updated' } ]
